package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"cognito-batch-backend/db"
	"cognito-batch-backend/web/graph/model"
	"context"

	"gorm.io/gorm"
)

// StartBatchCreate is the resolver for the startBatchCreate field.
func (r *mutationResolver) StartBatchCreate(ctx context.Context, inputs []*model.UserInput) (*model.Job, error) {
	users := make([]db.User, 0, len(inputs))
	for _, input := range inputs {
		users = append(users, db.User{
			Email:     input.Email,
			Username:  input.Username,
			Name:      input.Name,
			CognitoID: input.CognitoID,
		})
	}

	job, err := r.JobService.StartBatchCreate(ctx, users)
	if err != nil {
		return nil, err
	}

	return toGraphQLJob(*job), nil
}

// CancelJob is the resolver for the cancelJob field.
func (r *mutationResolver) CancelJob(ctx context.Context, id string) (*model.Job, error) {
	job, err := r.JobService.CancelJob(ctx, id)
	if err != nil {
		return nil, err
	}

	return toGraphQLJob(*job), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.List(ctx)
	if err != nil {
		return nil, err
	}
	return toGraphQLUsers(users), nil
}

// UserByName is the resolver for the userByName field.
func (r *queryResolver) UserByName(ctx context.Context, name string) (*model.User, error) {
	user, err := r.UserService.GetByName(ctx, name)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, nil
	}
	return toGraphQLUser(*user), nil
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.Job, error) {
	job, err := r.JobService.GetByID(ctx, id)
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, nil
		}
		return nil, err
	}

	return toGraphQLJob(*job), nil
}

// ValidateUsers is the resolver for the validateUsers field.
func (r *queryResolver) ValidateUsers(ctx context.Context, inputs []*model.UserInput) (*model.ValidationResult, error) {
	users := make([]db.User, 0, len(inputs))
	for _, input := range inputs {
		users = append(users, db.User{
			Email:     input.Email,
			Username:  input.Username,
			Name:      input.Name,
			CognitoID: input.CognitoID,
		})
	}

	result, err := r.ValidationService.ValidateUsers(ctx, users)
	if err != nil {
		return nil, err
	}

	return toGraphQLValidationResult(result), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
