// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type Job struct {
	ID              string      `json:"id"`
	Status          JobStatus   `json:"status"`
	TotalCount      int         `json:"totalCount"`
	ProcessedCount  int         `json:"processedCount"`
	SuccessCount    int         `json:"successCount"`
	FailureCount    int         `json:"failureCount"`
	SourceObjectKey *string     `json:"sourceObjectKey,omitempty"`
	ExternalJobID   *string     `json:"externalJobId,omitempty"`
	StatusMessage   *string     `json:"statusMessage,omitempty"`
	Errors          []*JobError `json:"errors"`
}

type JobError struct {
	ID        string `json:"id"`
	RowNumber int    `json:"rowNumber"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Message   string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

type RowValidation struct {
	RowNumber int                 `json:"rowNumber"`
	Status    ValidationRowStatus `json:"status"`
	Errors    []*FieldError       `json:"errors"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Name      string  `json:"name"`
	CognitoID *string `json:"cognitoId,omitempty"`
}

type UserInput struct {
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Name      string  `json:"name"`
	CognitoID *string `json:"cognitoId,omitempty"`
}

type ValidationResult struct {
	Summary *ValidationSummary `json:"summary"`
	Rows    []*RowValidation   `json:"rows"`
}

type ValidationSummary struct {
	NewCount   int `json:"newCount"`
	ErrorCount int `json:"errorCount"`
}

type JobStatus string

const (
	JobStatusQueued    JobStatus = "QUEUED"
	JobStatusRunning   JobStatus = "RUNNING"
	JobStatusCompleted JobStatus = "COMPLETED"
	JobStatusFailed    JobStatus = "FAILED"
	JobStatusCanceled  JobStatus = "CANCELED"
)

var AllJobStatus = []JobStatus{
	JobStatusQueued,
	JobStatusRunning,
	JobStatusCompleted,
	JobStatusFailed,
	JobStatusCanceled,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusQueued, JobStatusRunning, JobStatusCompleted, JobStatusFailed, JobStatusCanceled:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ValidationRowStatus string

const (
	ValidationRowStatusNew   ValidationRowStatus = "NEW"
	ValidationRowStatusError ValidationRowStatus = "ERROR"
)

var AllValidationRowStatus = []ValidationRowStatus{
	ValidationRowStatusNew,
	ValidationRowStatusError,
}

func (e ValidationRowStatus) IsValid() bool {
	switch e {
	case ValidationRowStatusNew, ValidationRowStatusError:
		return true
	}
	return false
}

func (e ValidationRowStatus) String() string {
	return string(e)
}

func (e *ValidationRowStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ValidationRowStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ValidationRowStatus", str)
	}
	return nil
}

func (e ValidationRowStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ValidationRowStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ValidationRowStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
